[workspace]
resolver = "2"
members = [
	"apps/desktop/src-tauri",
	"crates/rendering",
	"crates/ffmpeg",
	"crates/utils",
	"crates/project",
]

[workspace.dependencies]
ffmpeg-next = { git = "https://github.com/CapSoftware/rust-ffmpeg", rev = "11f8d264bbc0" }
tauri = { version = "2.0.0-rc" }
