[workspace]
resolver = "2"
members = [
	"apps/desktop/src-tauri",
	"crates/rendering",
	"crates/ffmpeg",
	"crates/utils",
	"crates/project",
]

[workspace.dependencies]
ffmpeg-next = "7.1"
tauri = { version = "2.0.0-rc" }
