[workspace]
resolver = "2"
members = [
	"apps/desktop/src-tauri",
	"crates/rendering",
	"crates/ffmpeg",
	"crates/media",
	"crates/utils",
	"crates/project",
	"crates/editor",
]

[workspace.dependencies]
anyhow = "1.0.86"
ffmpeg = { package = "ffmpeg-next", git = "https://github.com/zmwangx/rust-ffmpeg", branch = "master" }
ffmpeg-sys-next = "7.1.0"
ffmpeg-next = "7.1.0"
tokio = { version = "1.39.3", features = [
	"macros",
	"process",
	"fs",
	"sync",
	"rt",
	"rt-multi-thread",
	"time",
] }
tauri = { version = "2.0.0-rc" }
