[package]
name = "cap-media"
version = "0.1.0"
description = "A modular multimedia processing library"
edition = "2021"
rust-version = "1.80"

[dependencies]
anyhow.workspace = true
cap-project = { path = "../project" }
cpal = "0.15.3"
ffmpeg.workspace = true
ffmpeg-sys-next.workspace = true
flume = "0.11.0"
indexmap = "2.5.0"
nokhwa = { git = "https://github.com/Brendonovich/nokhwa", rev = "2de5a760d5f1", features = [
	"input-avfoundation",
	"serialize",
] }
scap = { path = "../../../scap" }
# scap = { git = "https://github.com/CapSoftware/scap", rev = "691bd88798d3" }
serde = { version = "1", features = ["derive"] }
specta = "=2.0.0-rc.19"
thiserror = "1.0"
tracing = "0.1"

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.24.0"
core-foundation = "0.10.0"
nokhwa-bindings-macos = { git = "https://github.com/Brendonovich/nokhwa", rev = "2de5a760d5f1" }

[dev-dependencies]
ctrlc = "3.4"
smol = "2.0"
tracing-subscriber = "0.3"
