[package]
name = "cap"
version = "0.0.0"
description = "Effortless, instant screen sharing. Open source and cross-platform."
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }
ffmpeg-sidecar = { git = "https://github.com/CapSoftware/ffmpeg-sidecar", branch = "main" }

[dependencies]
tauri = { version = "=2.0.0-rc.0", features = [
	"macos-private-api",
	"devtools",
	"tray-icon",
] }
tauri-plugin-global-shortcut = "2.0.0-rc"
tauri-plugin-oauth = { git = "https://github.com/FabianLars/tauri-plugin-oauth", branch = "v2" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ffmpeg-sidecar = { git = "https://github.com/CapSoftware/ffmpeg-sidecar", branch = "main" }
cpal = "0.15.2"
which = "4.2.2"
tokio = { version = "1.35.1", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["io", "codec"] }
futures = "0.3.30"
reqwest = { version = "0.11.23", features = ["json", "multipart", "stream"] }
chrono = "0.4.33"
dotenvy_macro = "0.15.7"
byteorder = "1.4.3"
bytemuck = "1.14.3"
num-traits = "0.2.19"
indexmap = "2.2.6"
regex = "1"
scap = { git = "https://github.com/CapSoftware/scap" }
image = { version = "0.24.9", features = ["jpeg", "png", "webp"] }
sentry = "0.32.2"
fix-path-env = { git = "https://github.com/tauri-apps/fix-path-env-rs" }
winit = "0.29.15"
jpeg-encoder = "0.6.0"
nix = "0.20.0"
urlencoding = "2.1.2"
bytes = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-appender = "0.2"
sentry-tracing = "0.34.0"
keyboard-types = "0.7.0"
specta = "=2.0.0-rc.19"
tauri-specta = { version = "=2.0.0-rc.14", features = ["derive", "typescript"] }
specta-typescript = "0.0.6"
dirs = "5.0.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = [
	"fileapi",
	"winbase",
	"winnt",
	"handleapi",
] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
