[package]
name = "tauri-plugin-global-shortcut"
version = "1.0.0"
description = "Register global hotkeys listeners on your Tauri application."
edition = "2021"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tauri = { version = "1.6.1" }
log = "0.4.22"
thiserror = "1.0.63"

global-hotkey = { version = "0.5", features = ["serde"] }
