[package]
name = "desktop-solid"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "desktop_solid_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }
swift-rs = { version = "1.0.6", features = ["build"] }

[dependencies]
tauri = { version = "2.0.0-rc", features = ["protocol-asset"] }
tauri-plugin-shell = "2.0.0-rc"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
specta = "=2.0.0-rc.19"
tauri-specta = { version = "=2.0.0-rc.14", features = ["derive", "typescript"] }
specta-typescript = "0.0.6"
tauri-plugin-decorum = "1.0.0"
swift-rs = "1.0.6"
nokhwa = { git = "https://github.com/Brendonovich/nokhwa", rev = "2de5a760d5f1", features = [
	"input-avfoundation",
	"serialize",
] }
nokhwa-bindings-macos = { git = "https://github.com/Brendonovich/nokhwa", rev = "2de5a760d5f1" }
nix = { version = "0.29.0", features = ["fs"] }
tokio = { version = "1.39.2", features = ["macros", "process"] }
uuid = { version = "1.10.0", features = ["v4"] }
scap = { git = "https://github.com/CapSoftware/scap" }
objc2-app-kit = { version = "0.2.2", features = ["NSWindow", "NSResponder"] }
core-graphics = "0.24.0"
core-foundation = "0.10.0"
tauri-nspanel = { git = "https://github.com/ahkohd/tauri-nspanel", branch = "v2" }
ffmpeg-sidecar = { git = "https://github.com/CapSoftware/ffmpeg-sidecar", branch = "main" }
wgpu = "22.1.0"
bytemuck = { version = "1.7", features = ["derive"] }
image = "0.25.2"
tauri-plugin-fs = "2.0.0-rc.0"
futures-intrusive = "0.5.0"
anyhow = "1.0.86"
cocoa = "0.26.0"
objc = "0.2.7"
mp4 = "0.14.0"

cap-utils = { path = "../../../crates/utils" }
cap-project = { path = "../../../crates/project" }
cap-rendering = { path = "../../../crates/rendering" }
cap-ffmpeg = { path = "../../../crates/ffmpeg" }
axum = { version = "0.7.5", features = ["ws"] }
